### ISSUE TITLE
Hi, In [28]  lm.predict(X)  why not  lm.predict_proba(X) or both is correct?

### ISSUE THREAD

**Issue by Jarye0612** [avikumart/imbalanced-classification-problem-with-GAIN-LIFT-chart#1]

**Comment by avikumart** [comment]
Hi, both are correct, either way, it will give probabilistic output, I haven't saved outputs for this notebook but here I'm attaching the output of the line [28]. thanks for raising the issue.
<html>
<body>


actual | pred_prob
-- | --
0 | 0.873854
0 | 0.825633
1 | 0.689722
0 | 0.665803
0 | 0.658679


</body>
</html>
